# Generated by Django 2.2.7 on 2019-11-28 16:13

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleAdsData',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_clicks', models.PositiveIntegerField(default=0)),
                ('account_id', models.PositiveIntegerField()),
                ('adgroup_id', models.PositiveIntegerField()),
                ('keyword_id', models.PositiveIntegerField()),
                ('campaign_id', models.PositiveIntegerField()),
                ('impressions', models.PositiveIntegerField()),
                ('georgian_date', models.DateField()),
            ],
            options={
                'db_table': 'GoogleAdsData',
                'get_latest_by': 'georgian_date',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='WeatherData',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('weather_data', django.contrib.postgres.fields.jsonb.JSONField()),
                ('georgian_date', models.DateField()),
            ],
            options={
                'db_table': 'WeatherData',
                'get_latest_by': 'georgian_date',
                'managed': True,
            },
        ),
    ]
